parameters:
    database_driver: pdo_mysql
    database_host: 172.17.0.2
    database_port: ~
    database_name: symfony
    database_user: symfony
    database_password: symfony

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
